stages:
  - build
  - publish

build:
  tags:
    - docker
  image: docker:stable
  stage: build
  services:
    - docker:19.03.5-dind
  only:
    - branches
  except:
    - master
  before_script:
    - apk add --no-cache make
  script: make tag

publish:
  tags:
    - docker
  image: docker:stable
  stage: publish
  services:
    - docker:19.03.5-dind
  only:
    - master
  before_script:
    - apk add --no-cache make
  script: 
    - |
      make \
        crUsername="$CR_USERNAME" \
        crPassword="$CR_PASSWORD" \
        publish