name: CI/CD

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker Login
        if: github.ref == 'refs/heads/master'
        uses: docker/login-action@v2
        with:
          username: joshkeegan
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Format
        run: make format
      
      - name: Build
        run: make build
      
      - name: Publish
        if: github.ref == 'refs/heads/master'
        run: make publish